"""Список каналов для публикации

Revision ID: 3ad00c25bc93
Revises: 977404011842
Create Date: 2026-08-01 13:34:04.789660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad00c25bc93'
down_revision: Union[str, None] = '977404011842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('settings_id', sa.Integer(), nullable=False),
    sa.Column('chat', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=512), nullable=True),
    sa.Column('can_post', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['settings_id'], ['telegram_settings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat')
    )
    op.create_index(op.f('ix_telegram_channels_settings_id'), 'telegram_channels', ['settings_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_channels_settings_id'), table_name='telegram_channels')
    op.drop_table('telegram_channels')
    # ### end Alembic commands ###
