"""Картинки статей с подписями

Revision ID: 3ce57a0af67f
Revises: 1c99b1fdc7ea
Create Date: 2026-07-29 10:33:09.635211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce57a0af67f'
down_revision: Union[str, None] = '1c99b1fdc7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('caption_ru', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'url', name='uq_article_images_url')
    )
    op.create_index(op.f('ix_article_images_article_id'), 'article_images', ['article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_article_images_article_id'), table_name='article_images')
    op.drop_table('article_images')
    # ### end Alembic commands ###
