"""Настройки подключения к языковой модели

Revision ID: 55dec30568e5
Revises: 3ce57a0af67f
Create Date: 2026-07-29 10:42:13.335819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55dec30568e5'
down_revision: Union[str, None] = '3ce57a0af67f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_settings')
    # ### end Alembic commands ###
