"""Шаблоны промптов и привязка к источникам

Revision ID: 5b2d3f3067d6
Revises: 55dec30568e5
Create Date: 2026-08-01 08:08:50.974251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2d3f3067d6'
down_revision: Union[str, None] = '55dec30568e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_prompt_templates_is_default'), 'prompt_templates', ['is_default'], unique=False)
    op.add_column('sources', sa.Column('prompt_template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sources', 'prompt_templates', ['prompt_template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_column('sources', 'prompt_template_id')
    op.drop_index(op.f('ix_prompt_templates_is_default'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
