"""Публикация в Telegram

Revision ID: 977404011842
Revises: 11b8426dafc7
Create Date: 2026-08-01 13:00:20.288269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '977404011842'
down_revision: Union[str, None] = '11b8426dafc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_token', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.String(length=128), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('telegram_message_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('telegram_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'telegram_url')
    op.drop_column('posts', 'telegram_message_id')
    op.drop_table('telegram_settings')
    # ### end Alembic commands ###
