"""Загруженные вручную фото

Revision ID: da8c5f8ffe65
Revises: 5b2d3f3067d6
Create Date: 2026-08-01 08:11:10.973042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da8c5f8ffe65'
down_revision: Union[str, None] = '5b2d3f3067d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_images', sa.Column('local_file', sa.String(length=255), nullable=True))
    # У существующих строк колонки нет, поэтому добавляем со значением
    # по умолчанию, а затем снимаем его — дальше значение задаёт приложение.
    op.add_column(
        'article_images',
        sa.Column('is_uploaded', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column('article_images', 'is_uploaded', server_default=None)
    op.add_column('article_images', sa.Column('uploaded_by_id', sa.Integer(), nullable=True))
    op.alter_column('article_images', 'url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.create_foreign_key(None, 'article_images', 'users', ['uploaded_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article_images', type_='foreignkey')
    op.alter_column('article_images', 'url',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    op.drop_column('article_images', 'uploaded_by_id')
    op.drop_column('article_images', 'is_uploaded')
    op.drop_column('article_images', 'local_file')
    # ### end Alembic commands ###
